---

- name: update apt cache
  raw: apt-get update
  changed_when: false

- name: install dpkg packages
  raw: apt-get -y install {{ item }}
  with_items: dpkg_packages
  register: dpkg_output
  changed_when: "'additional disk space will be used' in dpkg_output.stdout"

- name: install pre apt packages
  apt: pkg={{ item }} state=present
  with_items: apt_packages