# provision_dev.yml
- hosts: 127.0.0.1
  sudo: yes
  vars:
    base_path: /vagrant/provisioning
    db_password: U7KOekqJOMvf3Uu
    db_name: future500
    db_sql: /sql/db.sql

  tasks:
  - name: Install Webserver
    action: apt pkg={{ item }} state=installed update_cache=yes
    with_items:
      - nginx
      - mysql-server
      - mysql-client
      - phpmyadmin
      - php5-fpm
      - php5-cli
      - php5-gd
      - php5-mcrypt
      - php5-mysql
      - php-apc

  - name: Set new MySQL root password
    mysql_user: user=root password={{ db_password }} host=localhost

  - name: Create database
    mysql_db: db={{ db_name }} state=present login_user=root login_password={{ db_password }}

  - name: Import SQL file to database
    mysql_db: db={{ db_name }} state=import target={{ base_path}}/{{ db_sql }} login_user=root login_password={{ db_password }}

  - name: Copy new sites-available config (nginx)
    copy: src={{ base_path }}/conf/nginx/sites-available/default_dev dest=/etc/nginx/sites-available/default

  - name: Copy new nginx config
    copy: src={{ base_path }}/conf/nginx/nginx.conf dest=/etc/nginx/nginx.conf

  - name: Copy new www config
    copy: src={{ base_path }}/conf/php5-fpm/www.conf dest=/etc/php5/fpm/pool.d/www.conf

  - name: Restart nginx
    service: name=nginx state=restarted

  - name: Restart php-fpm
    shell: /etc/init.d/php5-fpm restart