---

- name: Install MySQL server and client
  apt: pkg={{ item }} state=installed
  with_items:
    - mysql-server
    - mysql-client

- name: Delete anonymous MySQL server user
  mysql_user: user="" state=absent

- name: Remove the MySQL test database
  mysql_db: db=test state=absent