---

- name: Install MySQL server and client
  apt: pkg={{ item }} state=installed
  with_items:
    - mysql-server
    - mysql-client

- name: Set new MySQL root password
  mysql_user: user=root password=secret host=localhost

- name: Copy new my.cnf file with root password credentials
  template: src=.my.cnf.j2 dest=~/.my.cnf owner=root mode=0600

- name: Delete anonymous MySQL server user
  mysql_user: user="" state=absent

- name: Remove the MySQL test database
  mysql_db: db=test state=absent