---

- name: Install PHP
  apt: pkg={{ item }} state=installed update_cache=yes
  with_items:
    - php-apc
    - php5-fpm
    - php5-cli
    - php5-gd
    - php5-mcrypt
    - php5-mysql
    - php5-curl
    - php5-intl