security:
    firewalls:
        main:
            pattern: ^/
            anonymous: true
            form:
                login_path: /login
                check_path: /login_check
                default_target_path: /
            logout:
                logout_path: /logout
                target: /

    role_hierarchy:
        ROLE_ADMIN: [ ROLE_USER, ROLE_ALLOWED_TO_SWITCH ]

    access_control:
        - [ '^/login', 'IS_AUTHENTICATED_ANONYMOUSLY' ]
        - [ '^/(stats|mydevices|date)', 'ROLE_USER' ]
        - [ '^/admin', 'ROLE_ADMIN' ]