---

- name: create system user
  user: name={{ ec_system_user }} password="nonexisstant" generate_ssh_key=yes state=present
  register: user_output

- name: retrieve public key for ec system user
  command: cat /home/{{ ec_system_user }}/.ssh/id_rsa.pub
  changed_when: False
  when: user_output|changed
  register: ec_public_key
  notify: show public key

- name: add authorized key to system user
  authorized_key: user={{ ec_system_user }} key="{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

- name: copy project database
  copy: src=files/db.sql dest=/root/db.sql mode=600 owner=root group=root

- name: add project database
  mysql_db: name={{ ec_db_name }} state=present
  register: add_db_output
  notify: import database

- name: create database user
  mysql_user: name={{ ec_db_user }} password={{ ec_db_password }} priv={{ ec_db_name }}.*:ALL state=present
  when: add_db_output|changed

- name: copy new sites-available config
  template: src=templates/nginx.conf.j2 dest=/etc/nginx/sites-available/default owner=root mode=0644
  notify: restart nginx