# provision-ecclient-dev.yml
- hosts: client-development
  sudo: yes

  roles:
    - init
    - install_apt_packages
    - ansible-install
    - php
    - nginx
    - composer
    - mysql
    - energycentral